name: polarmon
description: 'PolarMon'
publish_to: 'none'

version: 0.2.0+4

environment:
  flutter: ^3.35.4
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  polar: 7.7.0
  fl_chart: 1.1.1
  wakelock_plus: 1.4.0
  intl: any
  path_provider: 2.1.5
  collection: any
  flutter_form_builder: 10.2.0
  form_builder_validators: 11.2.0
  path: 1.9.1

  help_page:
    git:
      url: https://github.com/z80maniac/flutter_help_page.git
      ref: c6e76a5b30a33cce197f80643fbb5f44551ee86a

dev_dependencies:
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  generate: true
